### ISSUE TITLE
Validations infrastructure

### ISSUE THREAD

**Issue by jannahastings** [jannahastings/onto-spread-ed#12]
We need to implement validations that check the inputs in the spreadsheets and let the users know if there are problems. 

We need an event listener after editing for an overarching validation method that can be called regularly, within which other validation methods will be delegated. The validation should be implemented with Ajax, and should call a validations method on the server, passing as parameters (a) the current cell value, (b) the column header of the current cell, (b) the current row values and headers, and (c) the whole table. We will need this information to perform the validations. (We need both b and c because for some cell values it might not be possible to uniquely determine which is the current row.) The server checks the input and returns success or failure with a message. We do nothing on success, but on failure we should set the background of the cell in the table to a light red (the bootstrap alert-danger colour) and display the message in a pop-up if the user hovers over the cell. When the user clicks save, if there are still any validation errors the user should get a warning "There are validation errors, are you sure you want to save? ..." and then displaying the text of the outstanding validation errors in the same message window. They can still save after confirming though. 

For now create an empty validation method on the server and this logic. 

Cells that fail

**Comment by tomjuggler** [comment]
creating new branch "validations" for work on this feature
