### ISSUE TITLE
Save button and editing should be disabled while save is in progress

### ISSUE THREAD

**Issue by jannahastings** [jannahastings/onto-spread-ed#13]
The save button should be disabled while the save is taking place (not hidden, just disabled). Also, it shouldn't be possible to perform any additional edits while the save is in progress (in case there will be a merge conflict). Perhaps the best way to achieve this is to have a blocking popup "Save in progress" while the save is taking place?

**Comment by tomjuggler** [comment]
made a spinner "Saving..." which shows while saving is taking place. Just needs a bit of testing for edge case (eg. loss of internet) behaviour
