### ISSUE TITLE
Validations: Check relevant columns not empty

### ISSUE THREAD

**Issue by jannahastings** [jannahastings/onto-spread-ed#15]
We need to validate: 
- The label should never be empty. 
- The definition and parent should not be empty if the status is anything other than "Proposed" or "External". 
- AO sub-ontology should never be empty
- Curation status should never be empty

**Comment by tomjuggler** [comment]
Just updated validations branch with per-cell checks (while editing)

It might be better to do all of these for the whole row at once.

**Comment by jannahastings** [comment]
Now deployed
