### ISSUE TITLE
Visualisations: Initial infrastructure

### ISSUE THREAD

**Issue by jannahastings** [jannahastings/onto-spread-ed#16]
We will add a facility to visualise subsets of the content. Before we add the visualisations, we will need a page in which we will display the visualisations. 

We will need: 

- A new template visualise.html, with the usual headers and footers, and at the top some link options to view previously saved visualisations (these will be defined), underneath a blank space where we will put the visualisations
- A server-side method visualise( ... ) which will load the data required for the visualisation 
- Two buttons on the edit page: "Visualise sheet" and, when some rows are selected, "Visualise selection", which call the server-side method and open the visualise window *in a separate tab*

**Comment by tomjuggler** [comment]
I was just typing an email to ask what is next!

**Comment by tomjuggler** [comment]
I will start on this tomorrow.

**Comment by tomjuggler** [comment]
new branch created for this, graphVisualisation

For the visualise server method, will the data come via post from the front end (with up-to-date data) or from the saved spreadsheet on GitHub?

**Comment by jannahastings** [comment]
> new branch created for this, graphVisualisation

Great

> For the visualise server method, will the data come via post from the front end (with up-to-date data) or from the saved spreadsheet on GitHub?

The data from the sheet needs to come by post from the front end with the latest edits, so that changes can be visualised before they are saved. But this data isn't mandatory, because some visualisations will also be available even without editing a particular sheet.

**Comment by tomjuggler** [comment]
Great - I kind of thought so. I have started asking those lines already on
the new branch.

**Comment by tomjuggler** [comment]
*Along those lines

**Comment by jannahastings** [comment]
Deployed
