### ISSUE TITLE
Generate identifiers

### ISSUE THREAD

**Issue by jannahastings** [jannahastings/onto-spread-ed#17]
We need a facility to generate an identifier for rows that don't have identifiers. A button "Generate identifier" should appear when one or more rows that do not have an identifier, but do have label, definition and parent, are selected. The button should send the selected data via AJAX to a server method, that will return an array of string identifiers matching the number of selections. The IDs should then be populated from the returned values. 

The numeric part of the identifier will be globally unique, thus the last used number will be stored in a bucket with synchronized access.

**Comment by tomjuggler** [comment]
This one is done? Branch: "GenerateIdentifiers"

**Comment by jannahastings** [comment]
Deployed
