### ISSUE TITLE
Suggestions: infrastructure

### ISSUE THREAD

**Issue by jannahastings** [jannahastings/onto-spread-ed#19]
The columns "parent" and all the columns starting with "REL" should contain references to other entities that already exist in the ontology. Therefore, we can make suggestions when typing. The suggestions should include all the labels from the current sheet except the label of the current row, merged with all the labels from the last release (which we can get from the server). Suggestions should appear after the user has already typed 3 characters and should match anywhere in the label string (not just the beginning). Note that the columns starting with REL can have multiple values in them separated by semicolons so we should be able to activate suggestions multiple times.

**Comment by tomjuggler** [comment]
Development taking place on branch "autocomplete"

**Comment by jannahastings** [comment]
Deployed
