### ISSUE TITLE
Generate identifiers on save

### ISSUE THREAD

**Issue by jannahastings** [jannahastings/onto-spread-ed#20]
Now that the app can generate identifiers and keeps a record of the last used numeric ID, it will be difficult to synchronize if identifiers are added outside of the app (as was the pre-existing workflow). Thus, even if the user does not request an identifier for rows with metadata complete (i.e. having label, parent, and definition), we need to add this on save. 

Can we add this step on the server inside the save method -- check all rows that have label, parent and definition, but no identifier, and add a new identifier, after the pre-checks have passed, before saving the spreadsheet to the repository. Then we need to get those new identifiers back to the client who may continue with further editing on the same sheet.

**Comment by tomjuggler** [comment]
Working branch is: GenerateIdentifiersOnSave

**Comment by jannahastings** [comment]
Deployed
