### ISSUE TITLE
Download spreadsheet

### ISSUE THREAD

**Issue by jannahastings** [jannahastings/onto-spread-ed#24]
It would be useful to have a button in the spreadsheet editor that downloads the spreadsheet in Excel format as if it were being saved, i.e. the version that would get pushed to GitHub if the user clicked 'Save', but instead downloaded to the user's computer.

**Comment by tomjuggler** [comment]
Created a button which works - DownloadSpreadsheet branch

**Comment by jannahastings** [comment]
Deployed
