### ISSUE TITLE
Simultaneous editing

### ISSUE THREAD

**Issue by robertjwest** [jannahastings/onto-spread-ed#3]
Can we now use the new onto-spread-ed for simulataneous editing?

**Comment by jannahastings** [comment]
Yes -- well, almost. At the moment it will detect that there was a concurrent edit, and it will save the new change to a separate branch and tell you that there was a concurrent edit. It doesn't *yet* do the subsequent merge automatically (I am working on that) but afterwards I can pick up and merge the changes from the separate branch.

**Comment by robertjwest** [comment]
Ta - that will be very cool. Great chat with Bob yesterday - sorry I was
late. I hope it was OK asking if he might come along on the book chapter.
It sounded as though it would be right up his street.

Cheers

Robert



Robert West
robertwest100@gmail.com
07813916681

**Comment by jannahastings** [comment]
Deployed
